kind: pipeline
name: default

steps:
- name: master
  group: build
  image: plugins/docker
  settings:
    repo: belak/blog
    dockerfile: Dockerfile
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - master

- name: beta
  group: build
  image: plugins/docker
  settings:
    repo: belak/blog
    dockerfile: Dockerfile.beta
    tags: draft
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - master
