# This goes in a file named either `.vale.ini` or `_vale.ini`.
StylesPath = styles
MinAlertLevel = suggestion

# External packages
Packages = Google, Readability, alex, proselint, IBM

[*.{md,txt}]
BasedOnStyles = alex, proselint
