languageCode = "en-us"
title = "Coded by Kaleb"
baseURL = "https://coded.io/"
#disqusShortname = "coded"
SectionPagesMenu = "main"
googleAnalytics = "UA-37792462-2"

pygmentsCodeFences = true
pygmentsUseClasses = true

[menu]
  [[menu.main]]
    name = "Posts"
    weight = 1
    identifier = "posts"
    url = "/posts/"
  [[menu.main]]
    name = "Tags"
    weight = 2
    identifier = "tags"
    url = "/tags/"

[permalinks]
  posts = "/:year/:month/:title/"

[taxonomies]
  tag = "tags"
